services:
  nginx:
    image: bitnami/nginx:latest
    container_name: e_presensi_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf:ro
      - ../frontend:/frontend
    depends_on:
      - app
    networks:
      - be-network
    restart: unless-stopped

  app:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    container_name: e_presensi_app
    volumes:
      - ../:/app
    working_dir: /app/backend
    command: sh -c "node src/app.js"
    depends_on:
      - postgres
    networks:
      - be-network
      - db-network
    restart: unless-stopped

  postgres:
    image: bitnami/postgresql:latest
    container_name: e_presensi_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=e_presensi
      - POSTGRESQL_PERFORM_RESTORE=true
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
      - db-network
    restart: unless-stopped

volumes:
  postgres_data:
    external: true

networks:
  db-network:
    driver: bridge
  be-network:
    driver: bridge